name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest
    environment: crates.io

    steps:
      - uses: actions/checkout@v2
      # - name: Build
      #   run: cargo build
      - name: Run tests
        run: cargo test
      - name: Publish to crates.io
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: cargo login $CARGO_TOKEN && cargo publish
