name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: cargo-auto-publish
      # You may pin to the exact commit or the version.
      # uses: seunlanlege/cargo-auto-publish@12dfb09b683d500a97e239c169d033c8a5809321
      uses: seunlanlege/cargo-auto-publish@2
      with:
        # space de-limited paths to Cargo.toml files of crates you want to auto-publish
        toml: Cargo.toml # optional
